fix #258
pybliometrics-dev/pybliometrics pull request #259
Opened 2022-04-21 09:19 UTC by raffaem

fix #258

2022-04-26 09:58 UTC, Michael-E-Rose commented
The `"".join(filter(str.isdigit, item["$"])` bit is good, but to wrap all of this in a try-except makes the code just too complex.

Why not just always use this expression? `filter()` is lightning fast and it can capture whatever non-digits there might be.

```
@property
def classificationgroup(self) -> Optional[List[Tuple[int, int]]]:
    """List with (subject group ID, number of documents)-tuples."""
    path = ['classificationgroup', 'classifications', 'classification']
    out = [(int("".join(filter(str.isdigit, item["$"])))
            int(item['@frequency']))
           for item in listify(chained_get(self._profile, path, []))]
    return out or None
```

2022-04-26 17:16 UTC, raffaem commented
How does it look now?

2022-04-27 12:17 UTC, Michael-E-Rose commented
Ah, you created an anonymous function for this. Also nice.

But why not making it a proper function? I have the feeling it might be used again later. That is, you just put the function in https://github.com/pybliometrics-dev/pybliometrics/blob/master/pybliometrics/scopus/utils/parse_content.py and import in this place. To comply with the names of the other function, what about filter_digits()?

2022-04-28 07:40 UTC, Michael-E-Rose requested changes

2022-04-28 07:40 UTC, Michael-E-Rose commented on pybliometrics/scopus/utils/parse_content.py
> +    return "".join(filter(str.isdigit, s))
Short docstring please

2022-04-28 07:40 UTC, Michael-E-Rose commented on pybliometrics/scopus/author_retrieval.py
> +    parse_date_created, filter_digits
Sort alphabetically please

2022-04-28 20:24 UTC, Michael-E-Rose approved these changes

2022-04-28 20:25 UTC, merged

2022-04-28 20:25 UTC, Michael-E-Rose commented
Thanks for this!