Feat 329: Implement ScienceDirect `ArticleRetrieval` API
pybliometrics-dev/pybliometrics pull request #331
Opened 2024-05-11 14:00 UTC by nils-herrmann

The following features were implemented:

- `ArticleRetrieval` API
- Test for the `ArticleRetrieval` API
- Change of structure of the library. Now both science direct and scopus import the utils, superclasses and exceptions from pybliometrics

2024-05-28 07:49 UTC, Michael-E-Rose requested changes

2024-05-28 07:49 UTC, Michael-E-Rose commented on pybliometrics/__init__.py
Is it necessary to import utils and superclasses here? 
I strictly prefer a solution where this is not necessary. Otherwise users can directly access them, which is not necessary.

2024-05-28 07:49 UTC, Michael-E-Rose commented on pybliometrics/sciencedirect/__init__.py
Add empty line at the end

2024-05-28 07:49 UTC, Michael-E-Rose commented on pybliometrics/sciencedirect/article_retrieval.py
Sort imports alphabetically

2024-05-28 07:49 UTC, Michael-E-Rose commented on pybliometrics/sciencedirect/article_retrieval.py
When you return lists, always make sure that empty lists become `None`. For instance, create a list object, then `return list_obj or None`.

2024-06-02 10:49 UTC, nils-herrmann commented on pybliometrics/__init__.py
Import is not necessary

2024-08-06 15:23 UTC, Michael-E-Rose commented
Now is the time to integrate ScienceDirect. However, there are quite some merge conflicts. Can you resolve them please?

2024-08-12 10:06 UTC, Michael-E-Rose approved these changes

2024-08-12 10:19 UTC, Michael-E-Rose approved these changes

2024-08-12 10:20 UTC, merged